name: PureChat
main: _64FF00\PureChat\PureChat
version: 2.0.2
api: [4.0.0]
load: POSTWORLD
author: [Vecnavium , 64FF00]
depend: [PurePerms]
softdepend: [FactionsPro, XeviousPE-Factions]
commands:
  setformat:
    description: "Allows you to set default chat format of a PurePerms group"
    permission: pchat.command.setformat
  setnametag:
    description: "Allows you to set default nametag of a PurePerms group"
    permission: pchat.command.setnametag
  setprefix:
    description: "Allows you to set your PureChat prefix"
    permission: pchat.command.setprefix
  setsuffix:
    description: "Allows you to set your PureChat suffix"
    permission: pchat.command.setsuffix	
permissions:
  pchat:
    default: op
    description: "PureChat by 64FF00! (Twitter: @64FF00)"
  pchat.command:
    default: op
    description: "Allows you to use all PureChat commands."
  pchat.command.setformat:
    default: op
    description: "Allows you to set default chat format of a PurePerms group"
  pchat.command.setnametag:
    default: op
    description: "Allows you to set default nametag of a PurePerms group"
  pchat.command.setprefix:
    default: op
    description: "Allows you to set your PureChat prefix"
  pchat.command.setsuffix:
    default: op
    description: "Allows you to set your PureChat suffix"
  pchat.coloredMessages:
    default: op
    description: "Allows you to use colors in chat"
